#!/bin/bash

cat <<EOF > $SNAP_DATA/haproxy.cfg
listen stats
  bind *:8080
  mode http
  server www 127.0.0.1:5042 check
EOF

# Make sure we have a empty logfile on a clean install
touch $SNAP_DATA/provision.log

snapctl set haproxy-password=$(< /dev/urandom tr -dc A-Z-a-z-0-9 | head -c12)
snapctl set www-token=$(< /dev/urandom tr -dc A-Z-a-z-0-9 | head -c12)
snapctl set lxd-method=remote
